### ISSUE TITLE
Updates per meeting with AERPAW team - AUGUST

### ISSUE THREAD

**Issue by capasfield** [AERPAW-Platform-Control/aerpaw-portal#16]
[Meeting agenda with notes](https://docs.google.com/document/d/1VkKVLQERkPfOiFCRkIT1MRBMjcOeu9UbGPSt7nA-Uak/edit#)
[Folder with meeting recordings](https://drive.google.com/drive/folders/1HXpQnyMatAvOQLmRGiAh-kmxH9CWK8m3?usp=sharing)

- [x] Research server name that was seen in the URL when Sonali was walking us through her screens
    - Suspect it was due to data version mis-match between schema deployments - will keep an eye out for future instances of this during version migrations
- [x]  Delete older test data that was created prior to the last batch of changes. Flush all except users and resources.
- [x] provide documentation: started in `examples/code` directory
    - refresh tokens
    - python requests library
- [x] Create an API to remove the task of delivering an OVPN file and IPs (which could then be downloaded by the experimenter)
  - [x] `/experiment-files` endpoint - register experiment related files (OVPN, IP list, etc.)
  - [x] `/experiments/{int:pk}/files` endpoint - linked files pertaining to a specific experiment

Task for NCSU:

- [x] add stop/start session to [diagrams]([Portal C-F Interactions](https://docs.google.com/presentation/d/1cps_nSy29YezMwpzIw3KBKzxVa3L55CWDBj6pBtC9Gc/edit#slide=id.g13feb37dbac_1_7)) (trying to capture the action that has to happen in between the flows) - reference #15 
    - Preflight validation
    - Preflight Logic
    - Transition action
    - Update state
- [x] Begin to define the protocols for which the Portal would be requested to perform any actions on the User's behalf outside of the Portal itself (e.g. automation)
    - For example,  when a User is ready to "initiate development" what data is sent where using which credential?
    - This is the precursor to "automation" and all User/Experiment/Data requirements should be identified such that they can be programmatically checked for at each step or stage along an Experiment's life cycle

**Comment by mjstealey** [comment]
completed and deployed
