### ISSUE TITLE
Wrong Menu behavior?

### ISSUE THREAD

**Issue by rudradutta** [AERPAW-Platform-Control/aerpaw-portal#35]
This is while testing on the v2 Portal instance on 152.14.78.30, logged in as rdutta@ncsu.edu .  "Operators" --> "Experiment Sessions" seems to lead back to the front page (I had expected it would give me a - currently possibly blank - list of Sessions, with the option to view/edit/add, similar to how "Experiment Files" does).

**Comment by mjstealey** [comment]
Going to comment out the view in the nav-bar for now

This information is available via the API, but has not yet been ported to a UI element 
- Can add as a work item is deemed useful

**Comment by mjstealey** [comment]
removed from navbar view, to be added as future work item if desired
