### ISSUE TITLE
Raw JSON output still visible to all

### ISSUE THREAD

**Issue by rudradutta** [AERPAW-Platform-Control/aerpaw-portal#36]
I believe the intent was to eventually (maybe not yet) to hide the raw JSON output for the query at the bottom of each rendered page from Experimenters and PIs, but show them to Operators and Site Admins.  At this time, it seems it is still being shown to Experimenters at least.  Testing on 152.14.78.30, as rudra957@gmail.com .

**Comment by mjstealey** [comment]
@rudradutta - This is tied to the `DJANGO_DEBUG` setting in the `.env` file

```
# Django settings
export PYTHONPATH=./:./venv:./.venv
export DJANGO_ALLOWED_HOSTS='127.0.0.1'
export DJANGO_SECRET_KEY='xxxx...xxxxx'
export DJANGO_DEBUG=true                          <-- This line - set to false to suppress
export DJANGO_LOG_LEVEL='DEBUG'
export DJANGO_SESSION_COOKIE_AGE='14400'
export DJANGO_TIME_ZONE='America/New_York'
```

Specific roles can be allowed to always see the output
- always display for role: `site_admin`
- can add for role: `operators` as well if desired?

**Comment by mjstealey** [comment]
per request
- operator and site_admin always see the JSON debug output at the bottom of the page
- experimenter and pi only see the debug output if `DJANGO_DEBUG=true`, otherwise it is not displayed

deployed as described above
