### ISSUE TITLE
Non-Experimenter available to add to Project as member

### ISSUE THREAD

**Issue by rudradutta** [AERPAW-Platform-Control/aerpaw-portal#37]
I am not sure what the desired/planned functionality was in this context.  When a User first registers as an AERPAW User, they are not even an Experimenter.  (They have to view AUP, then request the Experimenter Role.)  At this stage, I thought they would be unavailable to add to Projects as Members, but it seems they show up in the list.

Testing on 152.14.78.30 (user-web-portal.aerpaw.ncsu.edu), logged in as rdutta@ncsu.edu, the no-Role User in question was aerpaw-tester-none.

**Comment by rudradutta** [comment]
I think this is okay; such non-Experimenters are VISIBLE in the list, but an attempt to add them as a Member to a Project fails (although it fails silently, so it took me a while to realize that that is what was happening here).

I will leave this open in case it is useful to track the issue that an informative failure message could be useful here, but please feel free to close it if it seems that adding such a message would be beyond the scope of the current work (as it well may be).

**Comment by mjstealey** [comment]
@rudradutta - This is correct, the API will block non-experimenters from being added to projects. I will add the appropriate filter to the UI so they will no longer be seen as options

**Comment by mjstealey** [comment]
UI filtering has been added and deployed
