### ISSUE TITLE
Repeated try apparently needed for login for first-time registrants

### ISSUE THREAD

**Issue by rudradutta** [AERPAW-Platform-Control/aerpaw-portal#38]
I try logging in with a new User ID, and when I do so, it returns me to the front page, with "Login" still showing at top right.  Then I try to do so again, again get to the second page, then click the "Log On" button in the "Select Identity Provider" box, then it brings me straight back to the front page already logged on - just as if the first time had succeeded (but if I don't start this second attempt it does not actually let me in).

**Comment by mjstealey** [comment]
For now, document this behavior in red text on the login page

**Comment by mjstealey** [comment]
denoted on login page and along with email should mitigate against most confusion - ultimately should have a more formal sign-up/registration process though
