### ISSUE TITLE
Difficult to manage multiple identities from Google on same browser even after logout

### ISSUE THREAD

**Issue by rudradutta** [AERPAW-Platform-Control/aerpaw-portal#39]
This is likely related to #38 , and have to do with the browser behavior, and perhaps not something much can be done about, but documenting in case it is.

Also on 152.14.78.30, logged in as aerpaw.tester.pi@gmail.com, using Google Chrome browser.

I log in, then log out, close that browser window (but other Chrome windows on other sites remain open).  I access the Portal again, and get the Login page - I click "Login", choose "Google" again as Identify Provider, and then instead of being presented with Google's site or dialog to choose an identity, I get logged right in with whatever Google identity I last logged in with.  I cannot switch to a different AERPAW User account (with a different Google ID).

If I Quit the Chrome application altogether after logging out of AERPAW, and then do this again, then I again get to choose which Google ID I want to use, as expected.

This may be only an issue when the Identity Provider is Google, and the browser is Chrome; in which case it's not of much importance.  I have no way to generate multiple arbitrary identities with any other identity provider, so have no way to check.  Anyway logging in from the same computer and same browser with different identities in quick succession is probably just an artifact of testing - may not occur frequently in real use.

**Comment by mjstealey** [comment]
Hard to discern what a user chooses to do client side with their browser and enforce anything meaningful ... we can only provide suggested practice for interacting with the portal in a sensible way

**Comment by mjstealey** [comment]
not within the application scope to manage for the user ... closing
