### ISSUE TITLE
No email generated after Role request is approved

### ISSUE THREAD

**Issue by rudradutta** [AERPAW-Platform-Control/aerpaw-portal#42]
After Site Admin approves an outstanding Role request, an email notification needs to be generated to the User who made the request (since this is a human action, and therefore likely takes days).  This seems not to be happening.

I realize this was not in the list of emails we listed in the Googledoc  we made for this purpose, but I think we left this out (like many others) which has been getting generated by the v1 Portal.  Please feel free to add it to that document, if we want that document to become a comprehensive list of all such required mails.

I did not check what would happen if a Role request were to be rejected - an email is required in that case too (perhaps even more so, since the User would not be able to tell from any change in the Portal).

**Comment by mjstealey** [comment]
deployed
